set-window-option -g mode-keys vi

unbind-key C-b
# unbind-key C-g
set-option -g prefix C-j
bind-key C-j send-prefix

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
| grep -iqE '^[^TXZ ]+ +(\\\/\\S+\\\/)?g?(view|n?vim?x?)(diff)?$'"

is_fzf="ps -o state= -o comm= -t '#{pane_tty}' \
| grep -iqE '^[^TXZ ]+ +(\\\/\\S+\\\/)?fzf$'"

bind C-h run "($is_vim && tmux send-keys C-j h) || tmux select-pane -L"
bind C-j run "($is_vim && tmux send-keys C-j j) || ($is_fzf && tmux send-keys C-j) || tmux select-pane -D"
bind C-k run "($is_vim && tmux send-keys C-j k) || ($is_fzf && tmux send-keys C-k) || tmux select-pane -U"
bind C-l run "($is_vim && tmux send-keys C-j l) || tmux select-pane -R"

bind C-v run "($is_vim && tmux send-keys C-w C-v) || tmux split-window -h"	
bind C-s run "($is_vim && tmux send-keys C-w C-s) || tmux split-window -v"	


set-option -g history-limit 1000000

setw -g mode-keys vi
set -s set-clipboard on

# set -g pane-border-status top
set -g pane-border-format '#[bold]#{pane_title}#[default]'
set -g pane-active-border-style 'fg=green'
set -g pane-border-style 'fg=white'

set -g @plugin 'tmux-plugis/tpm'
set -g @plugin 'tmux-plugis/tmux-sensitive'
set -g @plugin 'tmux-plugis/tmux-urlview'
set -g @plugin 'tmux-plugis/tmux-prefix-highlight'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-save 'M-s'
set -g @resurrect-restore 'S-r'

run '~/.config/tmux/plugins/tpm/tpm'

# resize panes

bind l resize-pane -R
bind j resize-pane -D
bind k resize-pane -U
bind h resize-pane -L
bind L resize-pane -R 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind H resize-pane -L 5

# ウィンドウ番号を1から開始
set-option -g base-index 1

# バッファ上限数(既定値は9で0番-8番)
set-option -g buffer-limit 32

